// <auto-generated />
using System;
using Channels.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Channels.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChannelsDbContext))]
    partial class ChannelsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("channels")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Channels.Domain.AttributeChannelMappings.AttributeChannelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_category_id");

                    b.Property<Guid>("CatalogSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_source_id");

                    b.Property<string>("ExternalAttributeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_attribute_id");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Marketplace", "CatalogCategoryId");

                    b.HasIndex("TenantId", "Marketplace", "CatalogCategoryId", "SourceType", "CatalogSourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_attribute_channel_mappings_tenant_id_marketplace_code_cata~1");

                    b.ToTable("attribute_channel_mappings", "channels");
                });

            modelBuilder.Entity("Channels.Domain.AttributeChannelMappings.AttributeValueChannelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeChannelMappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_channel_mapping_id");

                    b.Property<Guid>("CatalogValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_value_id");

                    b.Property<string>("ExternalValueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_value_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("AttributeChannelMappingId", "CatalogValueId")
                        .IsUnique();

                    b.ToTable("attribute_value_channel_mappings", "channels");
                });

            modelBuilder.Entity("Channels.Domain.CategoryChannelMappings.CategoryChannelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_category_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Marketplace");

                    b.HasIndex("TenantId", "CatalogCategoryId", "Marketplace")
                        .IsUnique();

                    b.HasIndex("TenantId", "Marketplace", "ExternalId");

                    b.ToTable("category_channel_mappings", "channels");
                });

            modelBuilder.Entity("Channels.Domain.Connections.MarketplaceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("ApiSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_secret");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<string>("SellerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("seller_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Marketplace")
                        .IsUnique();

                    b.ToTable("marketplace_connections", "channels");
                });

            modelBuilder.Entity("Channels.Domain.ExternalCatalog.ExternalAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalAttributeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_attribute_id");

                    b.Property<string>("ExternalCategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_category_id");

                    b.Property<string>("ExternalValueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_value_id");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("Marketplace", "ExternalCategoryId", "ExternalAttributeId", "ExternalValueId")
                        .IsUnique();

                    b.ToTable("external_attribute_values", "channels");
                });

            modelBuilder.Entity("Channels.Domain.ExternalCatalog.ExternalCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean")
                        .HasColumnName("is_leaf");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("ParentExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_external_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("Marketplace");

                    b.HasIndex("Name");

                    b.HasIndex("Marketplace", "ExternalId")
                        .IsUnique();

                    b.ToTable("external_categories", "channels");
                });

            modelBuilder.Entity("Channels.Domain.ExternalCatalog.ExternalCategoryAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_custom");

                    b.Property<string>("ExternalAttributeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_attribute_id");

                    b.Property<string>("ExternalCategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_category_id");

                    b.Property<bool>("IsSlicer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_slicer");

                    b.Property<bool>("IsVariant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_variant");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("Marketplace", "ExternalCategoryId");

                    b.HasIndex("Marketplace", "ExternalCategoryId", "ExternalAttributeId")
                        .IsUnique()
                        .HasDatabaseName("IX_external_category_attributes_marketplace_code_external_cat~1");

                    b.ToTable("external_category_attributes", "channels");
                });

            modelBuilder.Entity("Channels.Domain.Listings.ProductListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ContentDirtyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("content_dirty_at");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ExternalListingId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_listing_id");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<DateTimeOffset?>("LastSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_at");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("OfferDirtyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_dirty_at");

                    b.Property<string>("OfferHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("offer_hash");

                    b.Property<Guid>("ProductItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_item_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submission_reference");

                    b.Property<int>("SyncAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("sync_attempts");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("TenantId", "Marketplace")
                        .HasDatabaseName("ix_product_listings_dirty")
                        .HasFilter("content_dirty_at IS NOT NULL OR offer_dirty_at IS NOT NULL");

                    b.HasIndex("TenantId", "Marketplace", "ProductItemId")
                        .IsUnique();

                    b.ToTable("product_listings", "channels");
                });

            modelBuilder.Entity("Channels.Domain.ProductImports.ProductImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedProducts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_products");

                    b.Property<int>("ImportedProducts")
                        .HasColumnType("integer")
                        .HasColumnName("imported_products");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<int>("ProcessedProducts")
                        .HasColumnType("integer")
                        .HasColumnName("processed_products");

                    b.Property<int>("SkippedProducts")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_products");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TotalProducts")
                        .HasColumnType("integer")
                        .HasColumnName("total_products");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TenantId", "Marketplace", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("product_import_runs", "channels");
                });

            modelBuilder.Entity("Channels.Domain.Publications.ProductPublicationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer")
                        .HasColumnName("failed_items");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("integer")
                        .HasColumnName("processed_items");

                    b.Property<int>("PublishedItems")
                        .HasColumnType("integer")
                        .HasColumnName("published_items");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TenantId", "Marketplace", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("product_publication_runs", "channels");
                });

            modelBuilder.Entity("Channels.Domain.TaxonomySync.TaxonomySyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("marketplace_code");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("total_estimate");

                    b.HasKey("Id");

                    b.HasIndex("Marketplace");

                    b.HasIndex("Marketplace", "Status");

                    b.ToTable("taxonomy_sync_runs", "channels");
                });

            modelBuilder.Entity("Channels.Domain.ProductImports.ProductImportRun", b =>
                {
                    b.OwnsMany("Channels.Domain.ProductImports.ProductImportError", "Errors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Barcode")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("barcode");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("message");

                            b1.Property<string>("ProductMainId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("product_main_id");

                            b1.Property<Guid>("product_import_run_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("product_import_run_id");

                            b1.ToTable("product_import_run_errors", "channels");

                            b1.WithOwner()
                                .HasForeignKey("product_import_run_id");
                        });

                    b.Navigation("Errors");
                });

            modelBuilder.Entity("Channels.Domain.Publications.ProductPublicationRun", b =>
                {
                    b.OwnsMany("Channels.Domain.Publications.ProductPublicationError", "Errors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("message");

                            b1.Property<Guid>("ProductItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_item_id");

                            b1.Property<Guid>("product_publication_run_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("product_publication_run_id");

                            b1.ToTable("product_publication_run_errors", "channels");

                            b1.WithOwner()
                                .HasForeignKey("product_publication_run_id");
                        });

                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
