<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>pimly-product-imports-worker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Channels\Channels.Application\Channels.Application.csproj" />
    <ProjectReference Include="..\Modules\Channels\Channels.Infrastructure\Channels.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog.Application\Catalog.Application.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Pricing\Pricing.Application\Pricing.Application.csproj" />
    <ProjectReference Include="..\Modules\Pricing\Pricing.Infrastructure\Pricing.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Inventory\Inventory.Application\Inventory.Application.csproj" />
    <ProjectReference Include="..\Modules\Inventory\Inventory.Infrastructure\Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Media\Media.Application\Media.Application.csproj" />
    <ProjectReference Include="..\Modules\Media\Media.Infrastructure\Media.Infrastructure.csproj" />
  </ItemGroup>

</Project>
