<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationUrl>http://localhost:7000;https://localhost:7001</ApplicationUrl>
    <LaunchProfile>http</LaunchProfile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pimly.AspNetCore\Pimly.AspNetCore.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog.Api\Catalog.Api.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog.Application\Catalog.Application.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Api\Identity.Api.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Application\Identity.Application.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Media\Media.Api\Media.Api.csproj" />
    <ProjectReference Include="..\Modules\Media\Media.Application\Media.Application.csproj" />
    <ProjectReference Include="..\Modules\Media\Media.Infrastructure\Media.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Channels\Channels.Api\Channels.Api.csproj" />
    <ProjectReference Include="..\Modules\Channels\Channels.Application\Channels.Application.csproj" />
    <ProjectReference Include="..\Modules\Channels\Channels.Infrastructure\Channels.Infrastructure.csproj" />
  </ItemGroup>

</Project>
