// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attributes.sql

package tenantdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (
    key, label, data_type, value_source, metaobject_definition_id,
    inline_options, validation, binding_level, is_global
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, key, label, data_type, value_source, metaobject_definition_id, inline_options, validation, binding_level, is_global, created_at
`

type CreateAttributeParams struct {
	Key                    string          `json:"key"`
	Label                  string          `json:"label"`
	DataType               string          `json:"data_type"`
	ValueSource            string          `json:"value_source"`
	MetaobjectDefinitionID *uuid.UUID      `json:"metaobject_definition_id"`
	InlineOptions          json.RawMessage `json:"inline_options"`
	Validation             json.RawMessage `json:"validation"`
	BindingLevel           string          `json:"binding_level"`
	IsGlobal               bool            `json:"is_global"`
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute,
		arg.Key,
		arg.Label,
		arg.DataType,
		arg.ValueSource,
		arg.MetaobjectDefinitionID,
		arg.InlineOptions,
		arg.Validation,
		arg.BindingLevel,
		arg.IsGlobal,
	)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.ValueSource,
		&i.MetaobjectDefinitionID,
		&i.InlineOptions,
		&i.Validation,
		&i.BindingLevel,
		&i.IsGlobal,
		&i.CreatedAt,
	)
	return i, err
}

const getAttributeByID = `-- name: GetAttributeByID :one
SELECT id, key, label, data_type, value_source, metaobject_definition_id, inline_options, validation, binding_level, is_global, created_at FROM attributes WHERE id = $1
`

func (q *Queries) GetAttributeByID(ctx context.Context, id uuid.UUID) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByID, id)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.ValueSource,
		&i.MetaobjectDefinitionID,
		&i.InlineOptions,
		&i.Validation,
		&i.BindingLevel,
		&i.IsGlobal,
		&i.CreatedAt,
	)
	return i, err
}

const getAttributeByKey = `-- name: GetAttributeByKey :one
SELECT id, key, label, data_type, value_source, metaobject_definition_id, inline_options, validation, binding_level, is_global, created_at FROM attributes WHERE key = $1
`

func (q *Queries) GetAttributeByKey(ctx context.Context, key string) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByKey, key)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.ValueSource,
		&i.MetaobjectDefinitionID,
		&i.InlineOptions,
		&i.Validation,
		&i.BindingLevel,
		&i.IsGlobal,
		&i.CreatedAt,
	)
	return i, err
}

const listAttributes = `-- name: ListAttributes :many
SELECT id, key, label, data_type, value_source, metaobject_definition_id, inline_options, validation, binding_level, is_global, created_at FROM attributes ORDER BY created_at
`

func (q *Queries) ListAttributes(ctx context.Context) ([]Attribute, error) {
	rows, err := q.db.Query(ctx, listAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.ValueSource,
			&i.MetaobjectDefinitionID,
			&i.InlineOptions,
			&i.Validation,
			&i.BindingLevel,
			&i.IsGlobal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
