// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_attributes.sql

package tenantdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCategoryAttribute = `-- name: CreateCategoryAttribute :one
INSERT INTO category_attributes (category_id, attribute_id, required, marketplace_required, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, category_id, attribute_id, required, marketplace_required, sort_order
`

type CreateCategoryAttributeParams struct {
	CategoryID          uuid.UUID `json:"category_id"`
	AttributeID         uuid.UUID `json:"attribute_id"`
	Required            bool      `json:"required"`
	MarketplaceRequired bool      `json:"marketplace_required"`
	SortOrder           int32     `json:"sort_order"`
}

func (q *Queries) CreateCategoryAttribute(ctx context.Context, arg CreateCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, createCategoryAttribute,
		arg.CategoryID,
		arg.AttributeID,
		arg.Required,
		arg.MarketplaceRequired,
		arg.SortOrder,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.AttributeID,
		&i.Required,
		&i.MarketplaceRequired,
		&i.SortOrder,
	)
	return i, err
}

const deleteCategoryAttribute = `-- name: DeleteCategoryAttribute :execrows
DELETE FROM category_attributes WHERE id = $1
`

func (q *Queries) DeleteCategoryAttribute(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategoryAttribute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryAttribute = `-- name: GetCategoryAttribute :one
SELECT id, category_id, attribute_id, required, marketplace_required, sort_order FROM category_attributes WHERE id = $1
`

func (q *Queries) GetCategoryAttribute(ctx context.Context, id uuid.UUID) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, getCategoryAttribute, id)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.AttributeID,
		&i.Required,
		&i.MarketplaceRequired,
		&i.SortOrder,
	)
	return i, err
}

const listCategoryAttributeDefs = `-- name: ListCategoryAttributeDefs :many
SELECT
    ca.id            AS category_attribute_id,
    ca.required,
    ca.marketplace_required,
    ca.sort_order,
    a.id             AS attribute_id,
    a.key,
    a.label,
    a.data_type,
    a.value_source,
    a.binding_level,
    a.metaobject_definition_id,
    a.inline_options,
    a.validation
FROM category_attributes ca
JOIN attributes a ON a.id = ca.attribute_id
WHERE ca.category_id = $1
ORDER BY ca.sort_order
`

type ListCategoryAttributeDefsRow struct {
	CategoryAttributeID    uuid.UUID       `json:"category_attribute_id"`
	Required               bool            `json:"required"`
	MarketplaceRequired    bool            `json:"marketplace_required"`
	SortOrder              int32           `json:"sort_order"`
	AttributeID            uuid.UUID       `json:"attribute_id"`
	Key                    string          `json:"key"`
	Label                  string          `json:"label"`
	DataType               string          `json:"data_type"`
	ValueSource            string          `json:"value_source"`
	BindingLevel           string          `json:"binding_level"`
	MetaobjectDefinitionID *uuid.UUID      `json:"metaobject_definition_id"`
	InlineOptions          json.RawMessage `json:"inline_options"`
	Validation             json.RawMessage `json:"validation"`
}

func (q *Queries) ListCategoryAttributeDefs(ctx context.Context, categoryID uuid.UUID) ([]ListCategoryAttributeDefsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryAttributeDefs, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryAttributeDefsRow{}
	for rows.Next() {
		var i ListCategoryAttributeDefsRow
		if err := rows.Scan(
			&i.CategoryAttributeID,
			&i.Required,
			&i.MarketplaceRequired,
			&i.SortOrder,
			&i.AttributeID,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.ValueSource,
			&i.BindingLevel,
			&i.MetaobjectDefinitionID,
			&i.InlineOptions,
			&i.Validation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryAttributes = `-- name: ListCategoryAttributes :many
SELECT id, category_id, attribute_id, required, marketplace_required, sort_order FROM category_attributes WHERE category_id = $1 ORDER BY sort_order
`

func (q *Queries) ListCategoryAttributes(ctx context.Context, categoryID uuid.UUID) ([]CategoryAttribute, error) {
	rows, err := q.db.Query(ctx, listCategoryAttributes, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryAttribute{}
	for rows.Next() {
		var i CategoryAttribute
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AttributeID,
			&i.Required,
			&i.MarketplaceRequired,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryAttribute = `-- name: UpdateCategoryAttribute :one
UPDATE category_attributes
SET required = $2, marketplace_required = $3, sort_order = $4
WHERE id = $1
RETURNING id, category_id, attribute_id, required, marketplace_required, sort_order
`

type UpdateCategoryAttributeParams struct {
	ID                  uuid.UUID `json:"id"`
	Required            bool      `json:"required"`
	MarketplaceRequired bool      `json:"marketplace_required"`
	SortOrder           int32     `json:"sort_order"`
}

func (q *Queries) UpdateCategoryAttribute(ctx context.Context, arg UpdateCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, updateCategoryAttribute,
		arg.ID,
		arg.Required,
		arg.MarketplaceRequired,
		arg.SortOrder,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.AttributeID,
		&i.Required,
		&i.MarketplaceRequired,
		&i.SortOrder,
	)
	return i, err
}
