// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package tenantdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_code, category_id, title, status, attribute_values)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_code, category_id, title, status, attribute_values, created_at, updated_at
`

type CreateGroupParams struct {
	GroupCode       string          `json:"group_code"`
	CategoryID      *uuid.UUID      `json:"category_id"`
	Title           string          `json:"title"`
	Status          string          `json:"status"`
	AttributeValues json.RawMessage `json:"attribute_values"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.GroupCode,
		arg.CategoryID,
		arg.Title,
		arg.Status,
		arg.AttributeValues,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupCode,
		&i.CategoryID,
		&i.Title,
		&i.Status,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, group_code, category_id, title, status, attribute_values, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupCode,
		&i.CategoryID,
		&i.Title,
		&i.Status,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByCode = `-- name: GetGroupByCode :one
SELECT id, group_code, category_id, title, status, attribute_values, created_at, updated_at FROM groups WHERE group_code = $1
`

func (q *Queries) GetGroupByCode(ctx context.Context, groupCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByCode, groupCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupCode,
		&i.CategoryID,
		&i.Title,
		&i.Status,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupCodeExists = `-- name: GroupCodeExists :one
SELECT EXISTS(SELECT 1 FROM groups WHERE group_code = $1) AS exists
`

func (q *Queries) GroupCodeExists(ctx context.Context, groupCode string) (bool, error) {
	row := q.db.QueryRow(ctx, groupCodeExists, groupCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, group_code, category_id, title, status, attribute_values, created_at, updated_at FROM groups ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.GroupCode,
			&i.CategoryID,
			&i.Title,
			&i.Status,
			&i.AttributeValues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET title = $2, status = $3, category_id = $4, attribute_values = $5, updated_at = now()
WHERE id = $1
RETURNING id, group_code, category_id, title, status, attribute_values, created_at, updated_at
`

type UpdateGroupParams struct {
	ID              uuid.UUID       `json:"id"`
	Title           string          `json:"title"`
	Status          string          `json:"status"`
	CategoryID      *uuid.UUID      `json:"category_id"`
	AttributeValues json.RawMessage `json:"attribute_values"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.CategoryID,
		arg.AttributeValues,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.GroupCode,
		&i.CategoryID,
		&i.Title,
		&i.Status,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
