// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketplace.sql

package tenantdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMarketplaceAttributeMap = `-- name: DeleteMarketplaceAttributeMap :execrows
DELETE FROM marketplace_attribute_map WHERE id = $1
`

func (q *Queries) DeleteMarketplaceAttributeMap(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarketplaceAttributeMap, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMarketplaceCategoryMap = `-- name: DeleteMarketplaceCategoryMap :execrows
DELETE FROM marketplace_category_map WHERE id = $1
`

func (q *Queries) DeleteMarketplaceCategoryMap(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarketplaceCategoryMap, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMarketplaceAttributeMaps = `-- name: ListMarketplaceAttributeMaps :many
SELECT id, category_id, attribute_id, marketplace, marketplace_attribute_id, marketplace_attribute_name, required FROM marketplace_attribute_map WHERE category_id = $1 ORDER BY marketplace
`

func (q *Queries) ListMarketplaceAttributeMaps(ctx context.Context, categoryID uuid.UUID) ([]MarketplaceAttributeMap, error) {
	rows, err := q.db.Query(ctx, listMarketplaceAttributeMaps, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketplaceAttributeMap{}
	for rows.Next() {
		var i MarketplaceAttributeMap
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AttributeID,
			&i.Marketplace,
			&i.MarketplaceAttributeID,
			&i.MarketplaceAttributeName,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceCategoryMaps = `-- name: ListMarketplaceCategoryMaps :many
SELECT id, category_id, marketplace, marketplace_category_id, marketplace_category_path FROM marketplace_category_map WHERE category_id = $1 ORDER BY marketplace
`

func (q *Queries) ListMarketplaceCategoryMaps(ctx context.Context, categoryID uuid.UUID) ([]MarketplaceCategoryMap, error) {
	rows, err := q.db.Query(ctx, listMarketplaceCategoryMaps, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketplaceCategoryMap{}
	for rows.Next() {
		var i MarketplaceCategoryMap
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Marketplace,
			&i.MarketplaceCategoryID,
			&i.MarketplaceCategoryPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMarketplaceAttributeMap = `-- name: UpsertMarketplaceAttributeMap :one
INSERT INTO marketplace_attribute_map (category_id, attribute_id, marketplace, marketplace_attribute_id, marketplace_attribute_name, required)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (category_id, attribute_id, marketplace)
DO UPDATE SET marketplace_attribute_id = EXCLUDED.marketplace_attribute_id,
              marketplace_attribute_name = EXCLUDED.marketplace_attribute_name,
              required = EXCLUDED.required
RETURNING id, category_id, attribute_id, marketplace, marketplace_attribute_id, marketplace_attribute_name, required
`

type UpsertMarketplaceAttributeMapParams struct {
	CategoryID               uuid.UUID   `json:"category_id"`
	AttributeID              uuid.UUID   `json:"attribute_id"`
	Marketplace              string      `json:"marketplace"`
	MarketplaceAttributeID   pgtype.Text `json:"marketplace_attribute_id"`
	MarketplaceAttributeName pgtype.Text `json:"marketplace_attribute_name"`
	Required                 bool        `json:"required"`
}

func (q *Queries) UpsertMarketplaceAttributeMap(ctx context.Context, arg UpsertMarketplaceAttributeMapParams) (MarketplaceAttributeMap, error) {
	row := q.db.QueryRow(ctx, upsertMarketplaceAttributeMap,
		arg.CategoryID,
		arg.AttributeID,
		arg.Marketplace,
		arg.MarketplaceAttributeID,
		arg.MarketplaceAttributeName,
		arg.Required,
	)
	var i MarketplaceAttributeMap
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.AttributeID,
		&i.Marketplace,
		&i.MarketplaceAttributeID,
		&i.MarketplaceAttributeName,
		&i.Required,
	)
	return i, err
}

const upsertMarketplaceCategoryMap = `-- name: UpsertMarketplaceCategoryMap :one
INSERT INTO marketplace_category_map (category_id, marketplace, marketplace_category_id, marketplace_category_path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (category_id, marketplace)
DO UPDATE SET marketplace_category_id = EXCLUDED.marketplace_category_id,
              marketplace_category_path = EXCLUDED.marketplace_category_path
RETURNING id, category_id, marketplace, marketplace_category_id, marketplace_category_path
`

type UpsertMarketplaceCategoryMapParams struct {
	CategoryID              uuid.UUID   `json:"category_id"`
	Marketplace             string      `json:"marketplace"`
	MarketplaceCategoryID   pgtype.Text `json:"marketplace_category_id"`
	MarketplaceCategoryPath pgtype.Text `json:"marketplace_category_path"`
}

func (q *Queries) UpsertMarketplaceCategoryMap(ctx context.Context, arg UpsertMarketplaceCategoryMapParams) (MarketplaceCategoryMap, error) {
	row := q.db.QueryRow(ctx, upsertMarketplaceCategoryMap,
		arg.CategoryID,
		arg.Marketplace,
		arg.MarketplaceCategoryID,
		arg.MarketplaceCategoryPath,
	)
	var i MarketplaceCategoryMap
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Marketplace,
		&i.MarketplaceCategoryID,
		&i.MarketplaceCategoryPath,
	)
	return i, err
}
