// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package tenantdb

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (product_id, variant_id, url, alt_text, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, variant_id, url, alt_text, sort_order, created_at
`

type CreateMediaParams struct {
	ProductID uuid.UUID  `json:"product_id"`
	VariantID *uuid.UUID `json:"variant_id"`
	Url       string     `json:"url"`
	AltText   string     `json:"alt_text"`
	SortOrder int32      `json:"sort_order"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ProductID,
		arg.VariantID,
		arg.Url,
		arg.AltText,
		arg.SortOrder,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :execrows
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMedia = `-- name: GetMedia :one
SELECT id, product_id, variant_id, url, alt_text, sort_order, created_at FROM media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaByProduct = `-- name: ListMediaByProduct :many
SELECT id, product_id, variant_id, url, alt_text, sort_order, created_at FROM media WHERE product_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListMediaByProduct(ctx context.Context, productID uuid.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantID,
			&i.Url,
			&i.AltText,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMediaSortOrder = `-- name: NextMediaSortOrder :one
SELECT COALESCE(max(sort_order), -1)::int + 1 AS next FROM media WHERE product_id = $1
`

func (q *Queries) NextMediaSortOrder(ctx context.Context, productID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextMediaSortOrder, productID)
	var next int32
	err := row.Scan(&next)
	return next, err
}
