// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metaobjects.sql

package tenantdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMetaobjectDefinition = `-- name: CreateMetaobjectDefinition :one
INSERT INTO metaobject_definitions (key, label)
VALUES ($1, $2)
RETURNING id, key, label, created_at
`

type CreateMetaobjectDefinitionParams struct {
	Key   string `json:"key"`
	Label string `json:"label"`
}

func (q *Queries) CreateMetaobjectDefinition(ctx context.Context, arg CreateMetaobjectDefinitionParams) (MetaobjectDefinition, error) {
	row := q.db.QueryRow(ctx, createMetaobjectDefinition, arg.Key, arg.Label)
	var i MetaobjectDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const createMetaobjectEntry = `-- name: CreateMetaobjectEntry :one
INSERT INTO metaobject_entries (definition_id, values)
VALUES ($1, $2)
RETURNING id, definition_id, values, created_at
`

type CreateMetaobjectEntryParams struct {
	DefinitionID uuid.UUID       `json:"definition_id"`
	Values       json.RawMessage `json:"values"`
}

func (q *Queries) CreateMetaobjectEntry(ctx context.Context, arg CreateMetaobjectEntryParams) (MetaobjectEntry, error) {
	row := q.db.QueryRow(ctx, createMetaobjectEntry, arg.DefinitionID, arg.Values)
	var i MetaobjectEntry
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.Values,
		&i.CreatedAt,
	)
	return i, err
}

const createMetaobjectField = `-- name: CreateMetaobjectField :one
INSERT INTO metaobject_fields (definition_id, key, label, data_type)
VALUES ($1, $2, $3, $4)
RETURNING id, definition_id, key, label, data_type, created_at
`

type CreateMetaobjectFieldParams struct {
	DefinitionID uuid.UUID `json:"definition_id"`
	Key          string    `json:"key"`
	Label        string    `json:"label"`
	DataType     string    `json:"data_type"`
}

func (q *Queries) CreateMetaobjectField(ctx context.Context, arg CreateMetaobjectFieldParams) (MetaobjectField, error) {
	row := q.db.QueryRow(ctx, createMetaobjectField,
		arg.DefinitionID,
		arg.Key,
		arg.Label,
		arg.DataType,
	)
	var i MetaobjectField
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.CreatedAt,
	)
	return i, err
}

const getMetaobjectDefinitionByID = `-- name: GetMetaobjectDefinitionByID :one
SELECT id, key, label, created_at FROM metaobject_definitions WHERE id = $1
`

func (q *Queries) GetMetaobjectDefinitionByID(ctx context.Context, id uuid.UUID) (MetaobjectDefinition, error) {
	row := q.db.QueryRow(ctx, getMetaobjectDefinitionByID, id)
	var i MetaobjectDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getMetaobjectDefinitionByKey = `-- name: GetMetaobjectDefinitionByKey :one
SELECT id, key, label, created_at FROM metaobject_definitions WHERE key = $1
`

func (q *Queries) GetMetaobjectDefinitionByKey(ctx context.Context, key string) (MetaobjectDefinition, error) {
	row := q.db.QueryRow(ctx, getMetaobjectDefinitionByKey, key)
	var i MetaobjectDefinition
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getMetaobjectEntryByID = `-- name: GetMetaobjectEntryByID :one
SELECT id, definition_id, values, created_at FROM metaobject_entries WHERE id = $1
`

func (q *Queries) GetMetaobjectEntryByID(ctx context.Context, id uuid.UUID) (MetaobjectEntry, error) {
	row := q.db.QueryRow(ctx, getMetaobjectEntryByID, id)
	var i MetaobjectEntry
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.Values,
		&i.CreatedAt,
	)
	return i, err
}

const listMetaobjectDefinitions = `-- name: ListMetaobjectDefinitions :many
SELECT id, key, label, created_at FROM metaobject_definitions ORDER BY created_at
`

func (q *Queries) ListMetaobjectDefinitions(ctx context.Context) ([]MetaobjectDefinition, error) {
	rows, err := q.db.Query(ctx, listMetaobjectDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetaobjectDefinition{}
	for rows.Next() {
		var i MetaobjectDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetaobjectEntries = `-- name: ListMetaobjectEntries :many
SELECT id, definition_id, values, created_at FROM metaobject_entries WHERE definition_id = $1 ORDER BY created_at
`

func (q *Queries) ListMetaobjectEntries(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectEntry, error) {
	rows, err := q.db.Query(ctx, listMetaobjectEntries, definitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetaobjectEntry{}
	for rows.Next() {
		var i MetaobjectEntry
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.Values,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetaobjectFields = `-- name: ListMetaobjectFields :many
SELECT id, definition_id, key, label, data_type, created_at FROM metaobject_fields WHERE definition_id = $1 ORDER BY created_at
`

func (q *Queries) ListMetaobjectFields(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectField, error) {
	rows, err := q.db.Query(ctx, listMetaobjectFields, definitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetaobjectField{}
	for rows.Next() {
		var i MetaobjectField
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
