// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attribute struct {
	ID                     uuid.UUID          `json:"id"`
	Key                    string             `json:"key"`
	Label                  string             `json:"label"`
	DataType               string             `json:"data_type"`
	ValueSource            string             `json:"value_source"`
	MetaobjectDefinitionID *uuid.UUID         `json:"metaobject_definition_id"`
	InlineOptions          json.RawMessage    `json:"inline_options"`
	Validation             json.RawMessage    `json:"validation"`
	BindingLevel           string             `json:"binding_level"`
	IsGlobal               bool               `json:"is_global"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	Name      string             `json:"name"`
	Code      pgtype.Text        `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CategoryAttribute struct {
	ID                  uuid.UUID `json:"id"`
	CategoryID          uuid.UUID `json:"category_id"`
	AttributeID         uuid.UUID `json:"attribute_id"`
	Required            bool      `json:"required"`
	MarketplaceRequired bool      `json:"marketplace_required"`
	SortOrder           int32     `json:"sort_order"`
}

type Group struct {
	ID              uuid.UUID          `json:"id"`
	GroupCode       string             `json:"group_code"`
	CategoryID      *uuid.UUID         `json:"category_id"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	AttributeValues json.RawMessage    `json:"attribute_values"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MarketplaceAttributeMap struct {
	ID                       uuid.UUID   `json:"id"`
	CategoryID               uuid.UUID   `json:"category_id"`
	AttributeID              uuid.UUID   `json:"attribute_id"`
	Marketplace              string      `json:"marketplace"`
	MarketplaceAttributeID   pgtype.Text `json:"marketplace_attribute_id"`
	MarketplaceAttributeName pgtype.Text `json:"marketplace_attribute_name"`
	Required                 bool        `json:"required"`
}

type MarketplaceCategoryMap struct {
	ID                      uuid.UUID   `json:"id"`
	CategoryID              uuid.UUID   `json:"category_id"`
	Marketplace             string      `json:"marketplace"`
	MarketplaceCategoryID   pgtype.Text `json:"marketplace_category_id"`
	MarketplaceCategoryPath pgtype.Text `json:"marketplace_category_path"`
}

type MarketplaceListing struct {
	ID                   uuid.UUID          `json:"id"`
	ProductID            uuid.UUID          `json:"product_id"`
	Marketplace          string             `json:"marketplace"`
	MarketplaceProductID pgtype.Text        `json:"marketplace_product_id"`
	Status               string             `json:"status"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	Payload              json.RawMessage    `json:"payload"`
	Error                json.RawMessage    `json:"error"`
}

type Medium struct {
	ID        uuid.UUID          `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	VariantID *uuid.UUID         `json:"variant_id"`
	Url       string             `json:"url"`
	AltText   string             `json:"alt_text"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MetaobjectDefinition struct {
	ID        uuid.UUID          `json:"id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MetaobjectEntry struct {
	ID           uuid.UUID          `json:"id"`
	DefinitionID uuid.UUID          `json:"definition_id"`
	Values       json.RawMessage    `json:"values"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MetaobjectEntryMap struct {
	ID                    uuid.UUID   `json:"id"`
	EntryID               uuid.UUID   `json:"entry_id"`
	Marketplace           string      `json:"marketplace"`
	MarketplaceValueID    pgtype.Text `json:"marketplace_value_id"`
	MarketplaceValueLabel pgtype.Text `json:"marketplace_value_label"`
}

type MetaobjectField struct {
	ID           uuid.UUID          `json:"id"`
	DefinitionID uuid.UUID          `json:"definition_id"`
	Key          string             `json:"key"`
	Label        string             `json:"label"`
	DataType     string             `json:"data_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID                   uuid.UUID          `json:"id"`
	GroupID              uuid.UUID          `json:"group_id"`
	ProductSku           string             `json:"product_sku"`
	GroupingValueEntryID *uuid.UUID         `json:"grouping_value_entry_id"`
	Title                string             `json:"title"`
	AttributeValues      json.RawMessage    `json:"attribute_values"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	VariantTypes         json.RawMessage    `json:"variant_types"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     json.RawMessage    `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Variant struct {
	ID               uuid.UUID          `json:"id"`
	ProductID        uuid.UUID          `json:"product_id"`
	Barcode          string             `json:"barcode"`
	Gtin             pgtype.Text        `json:"gtin"`
	Mpn              pgtype.Text        `json:"mpn"`
	AxisValueEntryID *uuid.UUID         `json:"axis_value_entry_id"`
	AxisValue        pgtype.Text        `json:"axis_value"`
	Price            pgtype.Numeric     `json:"price"`
	CompareAtPrice   pgtype.Numeric     `json:"compare_at_price"`
	Stock            int32              `json:"stock"`
	AttributeValues  json.RawMessage    `json:"attribute_values"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Options          json.RawMessage    `json:"options"`
	Sku              pgtype.Text        `json:"sku"`
}

type VariantType struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	SelectionStyle string             `json:"selection_style"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type VariantValue struct {
	ID            uuid.UUID          `json:"id"`
	VariantTypeID uuid.UUID          `json:"variant_type_id"`
	Label         string             `json:"label"`
	Color         pgtype.Text        `json:"color"`
	ImageUrl      pgtype.Text        `json:"image_url"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Code          pgtype.Text        `json:"code"`
}
