// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package tenantdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (group_id, product_sku, grouping_value_entry_id, title, attribute_values, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, product_sku, grouping_value_entry_id, title, attribute_values, status, created_at, updated_at
`

type CreateProductParams struct {
	GroupID              uuid.UUID       `json:"group_id"`
	ProductSku           string          `json:"product_sku"`
	GroupingValueEntryID *uuid.UUID      `json:"grouping_value_entry_id"`
	Title                string          `json:"title"`
	AttributeValues      json.RawMessage `json:"attribute_values"`
	Status               string          `json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.GroupID,
		arg.ProductSku,
		arg.GroupingValueEntryID,
		arg.Title,
		arg.AttributeValues,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ProductSku,
		&i.GroupingValueEntryID,
		&i.Title,
		&i.AttributeValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, group_id, product_sku, grouping_value_entry_id, title, attribute_values, status, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ProductSku,
		&i.GroupingValueEntryID,
		&i.Title,
		&i.AttributeValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySku = `-- name: GetProductBySku :one
SELECT id, group_id, product_sku, grouping_value_entry_id, title, attribute_values, status, created_at, updated_at FROM products WHERE product_sku = $1
`

func (q *Queries) GetProductBySku(ctx context.Context, productSku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySku, productSku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ProductSku,
		&i.GroupingValueEntryID,
		&i.Title,
		&i.AttributeValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsByGroup = `-- name: ListProductsByGroup :many
SELECT id, group_id, product_sku, grouping_value_entry_id, title, attribute_values, status, created_at, updated_at FROM products WHERE group_id = $1 ORDER BY created_at
`

func (q *Queries) ListProductsByGroup(ctx context.Context, groupID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ProductSku,
			&i.GroupingValueEntryID,
			&i.Title,
			&i.AttributeValues,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productSkuExists = `-- name: ProductSkuExists :one
SELECT EXISTS(SELECT 1 FROM products WHERE product_sku = $1) AS exists
`

func (q *Queries) ProductSkuExists(ctx context.Context, productSku string) (bool, error) {
	row := q.db.QueryRow(ctx, productSkuExists, productSku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET title = $2, status = $3, attribute_values = $4, grouping_value_entry_id = $5, updated_at = now()
WHERE id = $1
RETURNING id, group_id, product_sku, grouping_value_entry_id, title, attribute_values, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID                   uuid.UUID       `json:"id"`
	Title                string          `json:"title"`
	Status               string          `json:"status"`
	AttributeValues      json.RawMessage `json:"attribute_values"`
	GroupingValueEntryID *uuid.UUID      `json:"grouping_value_entry_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.AttributeValues,
		arg.GroupingValueEntryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ProductSku,
		&i.GroupingValueEntryID,
		&i.Title,
		&i.AttributeValues,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
