// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error)
	CreateMetaobjectDefinition(ctx context.Context, arg CreateMetaobjectDefinitionParams) (MetaobjectDefinition, error)
	CreateMetaobjectEntry(ctx context.Context, arg CreateMetaobjectEntryParams) (MetaobjectEntry, error)
	CreateMetaobjectField(ctx context.Context, arg CreateMetaobjectFieldParams) (MetaobjectField, error)
	GetAttributeByID(ctx context.Context, id uuid.UUID) (Attribute, error)
	GetAttributeByKey(ctx context.Context, key string) (Attribute, error)
	GetMetaobjectDefinitionByID(ctx context.Context, id uuid.UUID) (MetaobjectDefinition, error)
	GetMetaobjectDefinitionByKey(ctx context.Context, key string) (MetaobjectDefinition, error)
	GetMetaobjectEntryByID(ctx context.Context, id uuid.UUID) (MetaobjectEntry, error)
	ListAttributes(ctx context.Context) ([]Attribute, error)
	ListMetaobjectDefinitions(ctx context.Context) ([]MetaobjectDefinition, error)
	ListMetaobjectEntries(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectEntry, error)
	ListMetaobjectFields(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectField, error)
}

var _ Querier = (*Queries)(nil)
