// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryAttribute(ctx context.Context, arg CreateCategoryAttributeParams) (CategoryAttribute, error)
	CreateMetaobjectDefinition(ctx context.Context, arg CreateMetaobjectDefinitionParams) (MetaobjectDefinition, error)
	CreateMetaobjectEntry(ctx context.Context, arg CreateMetaobjectEntryParams) (MetaobjectEntry, error)
	CreateMetaobjectField(ctx context.Context, arg CreateMetaobjectFieldParams) (MetaobjectField, error)
	DeleteAttribute(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCategoryAttribute(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMarketplaceAttributeMap(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMarketplaceCategoryMap(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMetaobjectDefinition(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMetaobjectEntry(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMetaobjectField(ctx context.Context, id uuid.UUID) (int64, error)
	GetAttributeByID(ctx context.Context, id uuid.UUID) (Attribute, error)
	GetAttributeByKey(ctx context.Context, key string) (Attribute, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryAttribute(ctx context.Context, id uuid.UUID) (CategoryAttribute, error)
	GetMetaobjectDefinitionByID(ctx context.Context, id uuid.UUID) (MetaobjectDefinition, error)
	GetMetaobjectDefinitionByKey(ctx context.Context, key string) (MetaobjectDefinition, error)
	GetMetaobjectEntryByID(ctx context.Context, id uuid.UUID) (MetaobjectEntry, error)
	ListAttributes(ctx context.Context) ([]Attribute, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoryAttributeDefs(ctx context.Context, categoryID uuid.UUID) ([]ListCategoryAttributeDefsRow, error)
	ListCategoryAttributes(ctx context.Context, categoryID uuid.UUID) ([]CategoryAttribute, error)
	ListMarketplaceAttributeMaps(ctx context.Context, categoryID uuid.UUID) ([]MarketplaceAttributeMap, error)
	ListMarketplaceCategoryMaps(ctx context.Context, categoryID uuid.UUID) ([]MarketplaceCategoryMap, error)
	ListMetaobjectDefinitions(ctx context.Context) ([]MetaobjectDefinition, error)
	ListMetaobjectEntries(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectEntry, error)
	ListMetaobjectFields(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectField, error)
	UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryAttribute(ctx context.Context, arg UpdateCategoryAttributeParams) (CategoryAttribute, error)
	UpdateMetaobjectEntry(ctx context.Context, arg UpdateMetaobjectEntryParams) (MetaobjectEntry, error)
	UpsertMarketplaceAttributeMap(ctx context.Context, arg UpsertMarketplaceAttributeMapParams) (MarketplaceAttributeMap, error)
	UpsertMarketplaceCategoryMap(ctx context.Context, arg UpsertMarketplaceCategoryMapParams) (MarketplaceCategoryMap, error)
}

var _ Querier = (*Queries)(nil)
