// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryAttribute(ctx context.Context, arg CreateCategoryAttributeParams) (CategoryAttribute, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateMetaobjectDefinition(ctx context.Context, arg CreateMetaobjectDefinitionParams) (MetaobjectDefinition, error)
	CreateMetaobjectEntry(ctx context.Context, arg CreateMetaobjectEntryParams) (MetaobjectEntry, error)
	CreateMetaobjectField(ctx context.Context, arg CreateMetaobjectFieldParams) (MetaobjectField, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error)
	DeleteAttribute(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCategoryAttribute(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMarketplaceAttributeMap(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMarketplaceCategoryMap(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMetaobjectDefinition(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMetaobjectEntry(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMetaobjectField(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteVariant(ctx context.Context, id uuid.UUID) (int64, error)
	GetAttributeByID(ctx context.Context, id uuid.UUID) (Attribute, error)
	GetAttributeByKey(ctx context.Context, key string) (Attribute, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryAttribute(ctx context.Context, id uuid.UUID) (CategoryAttribute, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupByCode(ctx context.Context, groupCode string) (Group, error)
	GetMetaobjectDefinitionByID(ctx context.Context, id uuid.UUID) (MetaobjectDefinition, error)
	GetMetaobjectDefinitionByKey(ctx context.Context, key string) (MetaobjectDefinition, error)
	GetMetaobjectEntryByID(ctx context.Context, id uuid.UUID) (MetaobjectEntry, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductBySku(ctx context.Context, productSku string) (Product, error)
	GetVariant(ctx context.Context, id uuid.UUID) (Variant, error)
	GroupCodeExists(ctx context.Context, groupCode string) (bool, error)
	ListAttributes(ctx context.Context) ([]Attribute, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoryAttributeDefs(ctx context.Context, categoryID uuid.UUID) ([]ListCategoryAttributeDefsRow, error)
	ListCategoryAttributes(ctx context.Context, categoryID uuid.UUID) ([]CategoryAttribute, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListMarketplaceAttributeMaps(ctx context.Context, categoryID uuid.UUID) ([]MarketplaceAttributeMap, error)
	ListMarketplaceCategoryMaps(ctx context.Context, categoryID uuid.UUID) ([]MarketplaceCategoryMap, error)
	ListMetaobjectDefinitions(ctx context.Context) ([]MetaobjectDefinition, error)
	ListMetaobjectEntries(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectEntry, error)
	ListMetaobjectFields(ctx context.Context, definitionID uuid.UUID) ([]MetaobjectField, error)
	ListProductsByGroup(ctx context.Context, groupID uuid.UUID) ([]Product, error)
	ListVariantsByProduct(ctx context.Context, productID uuid.UUID) ([]Variant, error)
	NextBarcodeSerial(ctx context.Context) (int64, error)
	ProductSkuExists(ctx context.Context, productSku string) (bool, error)
	UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryAttribute(ctx context.Context, arg UpdateCategoryAttributeParams) (CategoryAttribute, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateMetaobjectEntry(ctx context.Context, arg UpdateMetaobjectEntryParams) (MetaobjectEntry, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error)
	UpsertMarketplaceAttributeMap(ctx context.Context, arg UpsertMarketplaceAttributeMapParams) (MarketplaceAttributeMap, error)
	UpsertMarketplaceCategoryMap(ctx context.Context, arg UpsertMarketplaceCategoryMapParams) (MarketplaceCategoryMap, error)
	VariantBarcodeExists(ctx context.Context, barcode string) (bool, error)
}

var _ Querier = (*Queries)(nil)
