// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variant_types.sql

package tenantdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVariantType = `-- name: CreateVariantType :one
INSERT INTO variant_types (name, selection_style, sort_order)
VALUES ($1, $2, $3)
RETURNING id, name, selection_style, sort_order, created_at
`

type CreateVariantTypeParams struct {
	Name           string `json:"name"`
	SelectionStyle string `json:"selection_style"`
	SortOrder      int32  `json:"sort_order"`
}

func (q *Queries) CreateVariantType(ctx context.Context, arg CreateVariantTypeParams) (VariantType, error) {
	row := q.db.QueryRow(ctx, createVariantType, arg.Name, arg.SelectionStyle, arg.SortOrder)
	var i VariantType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SelectionStyle,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createVariantValue = `-- name: CreateVariantValue :one
INSERT INTO variant_values (variant_type_id, label, color, image_url, code, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, variant_type_id, label, color, image_url, sort_order, created_at, code
`

type CreateVariantValueParams struct {
	VariantTypeID uuid.UUID   `json:"variant_type_id"`
	Label         string      `json:"label"`
	Color         pgtype.Text `json:"color"`
	ImageUrl      pgtype.Text `json:"image_url"`
	Code          pgtype.Text `json:"code"`
	SortOrder     int32       `json:"sort_order"`
}

func (q *Queries) CreateVariantValue(ctx context.Context, arg CreateVariantValueParams) (VariantValue, error) {
	row := q.db.QueryRow(ctx, createVariantValue,
		arg.VariantTypeID,
		arg.Label,
		arg.Color,
		arg.ImageUrl,
		arg.Code,
		arg.SortOrder,
	)
	var i VariantValue
	err := row.Scan(
		&i.ID,
		&i.VariantTypeID,
		&i.Label,
		&i.Color,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}

const deleteVariantType = `-- name: DeleteVariantType :execrows
DELETE FROM variant_types WHERE id = $1
`

func (q *Queries) DeleteVariantType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariantType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVariantValue = `-- name: DeleteVariantValue :execrows
DELETE FROM variant_values WHERE id = $1
`

func (q *Queries) DeleteVariantValue(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariantValue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVariantTypeByID = `-- name: GetVariantTypeByID :one
SELECT id, name, selection_style, sort_order, created_at FROM variant_types WHERE id = $1
`

func (q *Queries) GetVariantTypeByID(ctx context.Context, id uuid.UUID) (VariantType, error) {
	row := q.db.QueryRow(ctx, getVariantTypeByID, id)
	var i VariantType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SelectionStyle,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantValueByID = `-- name: GetVariantValueByID :one
SELECT id, variant_type_id, label, color, image_url, sort_order, created_at, code FROM variant_values WHERE id = $1
`

func (q *Queries) GetVariantValueByID(ctx context.Context, id uuid.UUID) (VariantValue, error) {
	row := q.db.QueryRow(ctx, getVariantValueByID, id)
	var i VariantValue
	err := row.Scan(
		&i.ID,
		&i.VariantTypeID,
		&i.Label,
		&i.Color,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}

const listAllVariantValues = `-- name: ListAllVariantValues :many
SELECT id, variant_type_id, label, color, image_url, sort_order, created_at, code FROM variant_values ORDER BY variant_type_id, sort_order, created_at
`

func (q *Queries) ListAllVariantValues(ctx context.Context) ([]VariantValue, error) {
	rows, err := q.db.Query(ctx, listAllVariantValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantValue{}
	for rows.Next() {
		var i VariantValue
		if err := rows.Scan(
			&i.ID,
			&i.VariantTypeID,
			&i.Label,
			&i.Color,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantTypes = `-- name: ListVariantTypes :many
SELECT id, name, selection_style, sort_order, created_at FROM variant_types ORDER BY sort_order, created_at
`

func (q *Queries) ListVariantTypes(ctx context.Context) ([]VariantType, error) {
	rows, err := q.db.Query(ctx, listVariantTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantType{}
	for rows.Next() {
		var i VariantType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SelectionStyle,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantValues = `-- name: ListVariantValues :many
SELECT id, variant_type_id, label, color, image_url, sort_order, created_at, code FROM variant_values WHERE variant_type_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListVariantValues(ctx context.Context, variantTypeID uuid.UUID) ([]VariantValue, error) {
	rows, err := q.db.Query(ctx, listVariantValues, variantTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantValue{}
	for rows.Next() {
		var i VariantValue
		if err := rows.Scan(
			&i.ID,
			&i.VariantTypeID,
			&i.Label,
			&i.Color,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariantType = `-- name: UpdateVariantType :one
UPDATE variant_types SET name = $2, selection_style = $3, sort_order = $4 WHERE id = $1
RETURNING id, name, selection_style, sort_order, created_at
`

type UpdateVariantTypeParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	SelectionStyle string    `json:"selection_style"`
	SortOrder      int32     `json:"sort_order"`
}

func (q *Queries) UpdateVariantType(ctx context.Context, arg UpdateVariantTypeParams) (VariantType, error) {
	row := q.db.QueryRow(ctx, updateVariantType,
		arg.ID,
		arg.Name,
		arg.SelectionStyle,
		arg.SortOrder,
	)
	var i VariantType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SelectionStyle,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateVariantValue = `-- name: UpdateVariantValue :one
UPDATE variant_values SET label = $2, color = $3, image_url = $4, code = $5, sort_order = $6 WHERE id = $1
RETURNING id, variant_type_id, label, color, image_url, sort_order, created_at, code
`

type UpdateVariantValueParams struct {
	ID        uuid.UUID   `json:"id"`
	Label     string      `json:"label"`
	Color     pgtype.Text `json:"color"`
	ImageUrl  pgtype.Text `json:"image_url"`
	Code      pgtype.Text `json:"code"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateVariantValue(ctx context.Context, arg UpdateVariantValueParams) (VariantValue, error) {
	row := q.db.QueryRow(ctx, updateVariantValue,
		arg.ID,
		arg.Label,
		arg.Color,
		arg.ImageUrl,
		arg.Code,
		arg.SortOrder,
	)
	var i VariantValue
	err := row.Scan(
		&i.ID,
		&i.VariantTypeID,
		&i.Label,
		&i.Color,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.Code,
	)
	return i, err
}
