// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variants.sql

package tenantdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (
    product_id, sku, barcode, gtin, mpn, axis_value_entry_id, axis_value,
    price, compare_at_price, stock, attribute_values, options
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, product_id, barcode, gtin, mpn, axis_value_entry_id, axis_value, price, compare_at_price, stock, attribute_values, created_at, updated_at, options, sku
`

type CreateVariantParams struct {
	ProductID        uuid.UUID       `json:"product_id"`
	Sku              pgtype.Text     `json:"sku"`
	Barcode          string          `json:"barcode"`
	Gtin             pgtype.Text     `json:"gtin"`
	Mpn              pgtype.Text     `json:"mpn"`
	AxisValueEntryID *uuid.UUID      `json:"axis_value_entry_id"`
	AxisValue        pgtype.Text     `json:"axis_value"`
	Price            pgtype.Numeric  `json:"price"`
	CompareAtPrice   pgtype.Numeric  `json:"compare_at_price"`
	Stock            int32           `json:"stock"`
	AttributeValues  json.RawMessage `json:"attribute_values"`
	Options          json.RawMessage `json:"options"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Gtin,
		arg.Mpn,
		arg.AxisValueEntryID,
		arg.AxisValue,
		arg.Price,
		arg.CompareAtPrice,
		arg.Stock,
		arg.AttributeValues,
		arg.Options,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Barcode,
		&i.Gtin,
		&i.Mpn,
		&i.AxisValueEntryID,
		&i.AxisValue,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Options,
		&i.Sku,
	)
	return i, err
}

const deleteVariant = `-- name: DeleteVariant :execrows
DELETE FROM variants WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVariant = `-- name: GetVariant :one
SELECT id, product_id, barcode, gtin, mpn, axis_value_entry_id, axis_value, price, compare_at_price, stock, attribute_values, created_at, updated_at, options, sku FROM variants WHERE id = $1
`

func (q *Queries) GetVariant(ctx context.Context, id uuid.UUID) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariant, id)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Barcode,
		&i.Gtin,
		&i.Mpn,
		&i.AxisValueEntryID,
		&i.AxisValue,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Options,
		&i.Sku,
	)
	return i, err
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, barcode, gtin, mpn, axis_value_entry_id, axis_value, price, compare_at_price, stock, attribute_values, created_at, updated_at, options, sku FROM variants WHERE product_id = $1 ORDER BY created_at
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Barcode,
			&i.Gtin,
			&i.Mpn,
			&i.AxisValueEntryID,
			&i.AxisValue,
			&i.Price,
			&i.CompareAtPrice,
			&i.Stock,
			&i.AttributeValues,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Options,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBarcodeSerial = `-- name: NextBarcodeSerial :one
SELECT nextval('barcode_serial')::bigint AS serial
`

func (q *Queries) NextBarcodeSerial(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextBarcodeSerial)
	var serial int64
	err := row.Scan(&serial)
	return serial, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants
SET gtin = $2, mpn = $3, axis_value_entry_id = $4, axis_value = $5,
    price = $6, compare_at_price = $7, stock = $8, attribute_values = $9, updated_at = now()
WHERE id = $1
RETURNING id, product_id, barcode, gtin, mpn, axis_value_entry_id, axis_value, price, compare_at_price, stock, attribute_values, created_at, updated_at, options, sku
`

type UpdateVariantParams struct {
	ID               uuid.UUID       `json:"id"`
	Gtin             pgtype.Text     `json:"gtin"`
	Mpn              pgtype.Text     `json:"mpn"`
	AxisValueEntryID *uuid.UUID      `json:"axis_value_entry_id"`
	AxisValue        pgtype.Text     `json:"axis_value"`
	Price            pgtype.Numeric  `json:"price"`
	CompareAtPrice   pgtype.Numeric  `json:"compare_at_price"`
	Stock            int32           `json:"stock"`
	AttributeValues  json.RawMessage `json:"attribute_values"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.Gtin,
		arg.Mpn,
		arg.AxisValueEntryID,
		arg.AxisValue,
		arg.Price,
		arg.CompareAtPrice,
		arg.Stock,
		arg.AttributeValues,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Barcode,
		&i.Gtin,
		&i.Mpn,
		&i.AxisValueEntryID,
		&i.AxisValue,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.AttributeValues,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Options,
		&i.Sku,
	)
	return i, err
}

const variantBarcodeExists = `-- name: VariantBarcodeExists :one
SELECT EXISTS(SELECT 1 FROM variants WHERE barcode = $1) AS exists
`

func (q *Queries) VariantBarcodeExists(ctx context.Context, barcode string) (bool, error) {
	row := q.db.QueryRow(ctx, variantBarcodeExists, barcode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const variantSkuExists = `-- name: VariantSkuExists :one
SELECT EXISTS(SELECT 1 FROM variants WHERE sku = $1) AS exists
`

func (q *Queries) VariantSkuExists(ctx context.Context, sku pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, variantSkuExists, sku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
