// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package globaldb

import (
	"context"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (email, company_name, status)
VALUES ($1, $2, $3)
RETURNING id, email, company_name, status, created_at, approved_by
`

type CreateApplicationParams struct {
	Email       string `json:"email"`
	CompanyName string `json:"company_name"`
	Status      string `json:"status"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.Email, arg.CompanyName, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedBy,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, email, company_name, status, created_at, approved_by FROM applications WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedBy,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, email, company_name, status, created_at, approved_by FROM applications ORDER BY created_at DESC
`

func (q *Queries) ListApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CompanyName,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByStatus = `-- name: ListApplicationsByStatus :many
SELECT id, email, company_name, status, created_at, approved_by FROM applications WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByStatus(ctx context.Context, status string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CompanyName,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationStatus = `-- name: SetApplicationStatus :one
UPDATE applications
SET status = $2, approved_by = $3
WHERE id = $1
RETURNING id, email, company_name, status, created_at, approved_by
`

type SetApplicationStatusParams struct {
	ID         uuid.UUID  `json:"id"`
	Status     string     `json:"status"`
	ApprovedBy *uuid.UUID `json:"approved_by"`
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationStatus, arg.ID, arg.Status, arg.ApprovedBy)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CompanyName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedBy,
	)
	return i, err
}
