// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package globaldb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	CompanyName string             `json:"company_name"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ApprovedBy  *uuid.UUID         `json:"approved_by"`
}

type Membership struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	SchemaName        string             `json:"schema_name"`
	Status            string             `json:"status"`
	BarcodeTenantCode int32              `json:"barcode_tenant_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
}

type TenantModule struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Module    string             `json:"module"`
	Enabled   bool               `json:"enabled"`
	EnabledAt pgtype.Timestamptz `json:"enabled_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
