// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modules.sql

package globaldb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantModule = `-- name: GetTenantModule :one
SELECT id, tenant_id, module, enabled, enabled_at FROM tenant_modules WHERE tenant_id = $1 AND module = $2
`

type GetTenantModuleParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Module   string    `json:"module"`
}

func (q *Queries) GetTenantModule(ctx context.Context, arg GetTenantModuleParams) (TenantModule, error) {
	row := q.db.QueryRow(ctx, getTenantModule, arg.TenantID, arg.Module)
	var i TenantModule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Module,
		&i.Enabled,
		&i.EnabledAt,
	)
	return i, err
}

const listTenantModules = `-- name: ListTenantModules :many
SELECT id, tenant_id, module, enabled, enabled_at FROM tenant_modules WHERE tenant_id = $1 ORDER BY module
`

func (q *Queries) ListTenantModules(ctx context.Context, tenantID uuid.UUID) ([]TenantModule, error) {
	rows, err := q.db.Query(ctx, listTenantModules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantModule{}
	for rows.Next() {
		var i TenantModule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Module,
			&i.Enabled,
			&i.EnabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantModuleEnabled = `-- name: SetTenantModuleEnabled :one
UPDATE tenant_modules
SET enabled = $3, enabled_at = $4
WHERE tenant_id = $1 AND module = $2
RETURNING id, tenant_id, module, enabled, enabled_at
`

type SetTenantModuleEnabledParams struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	Module    string             `json:"module"`
	Enabled   bool               `json:"enabled"`
	EnabledAt pgtype.Timestamptz `json:"enabled_at"`
}

func (q *Queries) SetTenantModuleEnabled(ctx context.Context, arg SetTenantModuleEnabledParams) (TenantModule, error) {
	row := q.db.QueryRow(ctx, setTenantModuleEnabled,
		arg.TenantID,
		arg.Module,
		arg.Enabled,
		arg.EnabledAt,
	)
	var i TenantModule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Module,
		&i.Enabled,
		&i.EnabledAt,
	)
	return i, err
}

const upsertTenantModule = `-- name: UpsertTenantModule :one
INSERT INTO tenant_modules (tenant_id, module, enabled, enabled_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, module)
DO UPDATE SET enabled = EXCLUDED.enabled, enabled_at = EXCLUDED.enabled_at
RETURNING id, tenant_id, module, enabled, enabled_at
`

type UpsertTenantModuleParams struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	Module    string             `json:"module"`
	Enabled   bool               `json:"enabled"`
	EnabledAt pgtype.Timestamptz `json:"enabled_at"`
}

func (q *Queries) UpsertTenantModule(ctx context.Context, arg UpsertTenantModuleParams) (TenantModule, error) {
	row := q.db.QueryRow(ctx, upsertTenantModule,
		arg.TenantID,
		arg.Module,
		arg.Enabled,
		arg.EnabledAt,
	)
	var i TenantModule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Module,
		&i.Enabled,
		&i.EnabledAt,
	)
	return i, err
}
