// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package globaldb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error)
	GetFirstMembershipForUser(ctx context.Context, userID uuid.UUID) (Membership, error)
	GetMembershipByUserAndTenant(ctx context.Context, arg GetMembershipByUserAndTenantParams) (Membership, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTenantModule(ctx context.Context, arg GetTenantModuleParams) (TenantModule, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveTenants(ctx context.Context) ([]Tenant, error)
	ListApplications(ctx context.Context) ([]Application, error)
	ListApplicationsByStatus(ctx context.Context, status string) ([]Application, error)
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]Membership, error)
	ListTenantModules(ctx context.Context, tenantID uuid.UUID) ([]TenantModule, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (Application, error)
	SetTenantModuleEnabled(ctx context.Context, arg SetTenantModuleEnabledParams) (TenantModule, error)
	SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error)
	UpsertTenantModule(ctx context.Context, arg UpsertTenantModuleParams) (TenantModule, error)
}

var _ Querier = (*Queries)(nil)
