// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package globaldb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, schema_name, status, barcode_tenant_code, approved_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, schema_name, status, barcode_tenant_code, created_at, approved_at
`

type CreateTenantParams struct {
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	SchemaName        string             `json:"schema_name"`
	Status            string             `json:"status"`
	BarcodeTenantCode int32              `json:"barcode_tenant_code"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.SchemaName,
		arg.Status,
		arg.BarcodeTenantCode,
		arg.ApprovedAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Status,
		&i.BarcodeTenantCode,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, schema_name, status, barcode_tenant_code, created_at, approved_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Status,
		&i.BarcodeTenantCode,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, schema_name, status, barcode_tenant_code, created_at, approved_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Status,
		&i.BarcodeTenantCode,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, name, slug, schema_name, status, barcode_tenant_code, created_at, approved_at FROM tenants WHERE status = 'active' ORDER BY created_at
`

func (q *Queries) ListActiveTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SchemaName,
			&i.Status,
			&i.BarcodeTenantCode,
			&i.CreatedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, schema_name, status, barcode_tenant_code, created_at, approved_at FROM tenants ORDER BY created_at
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SchemaName,
			&i.Status,
			&i.BarcodeTenantCode,
			&i.CreatedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants SET status = $2, approved_at = $3 WHERE id = $1 RETURNING id, name, slug, schema_name, status, barcode_tenant_code, created_at, approved_at
`

type SetTenantStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.ID, arg.Status, arg.ApprovedAt)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Status,
		&i.BarcodeTenantCode,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}
